apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1 # Minimum number of replicas to scale down to
  maxReplicas: 5 # Maximum number of replicas to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75 # Scale up when average CPU usage exceeds 75%
